# Generated by Django 5.0.3 on 2024-04-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('update_date', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='course/speciality/')),
                ('update_date', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course/course/')),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('USD', '$'), ('UZS', "SO'M")], default='UZS', max_length=8)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField()),
                ('duration_hours', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('update_date', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('speciality', models.ManyToManyField(to='course.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='course/teacher/')),
                ('t_link', models.URLField(null=True)),
                ('f_link', models.URLField(null=True)),
                ('l_link', models.URLField(null=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.position')),
            ],
        ),
    ]
