# Generated by Django 5.0.3 on 2024-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_count',
            field=models.IntegerField(default=0),
        ),
    ]
