# Generated by Django 5.0.3 on 2024-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='f_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='l_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
