# Generated by Django 5.0.3 on 2024-04-20 16:36

import course.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_teacher_f_link_alter_teacher_l_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='df', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=course.helpers.SaveMediaFile.image_course),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='image',
            field=models.ImageField(upload_to=course.helpers.SaveMediaFile.image_speciality),
        ),
    ]
