# Generated by Django 5.0.3 on 2024-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_status_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1, max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
