# Generated by Django 5.0.3 on 2024-04-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
