# Generated by Django 5.0.3 on 2024-04-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1, max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
