# Generated by Django 5.0.3 on 2024-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
