# Generated by Django 5.0.3 on 2024-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default=1, upload_to='media/students/'),
            preserve_default=False,
        ),
    ]
